# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('HYD', 'HYDERABAD'), ('PUNE', 'PUNE')], max_length=50)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('MRNG', 'MORNING'), ('EVE', 'EVENINNG')], max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
