# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-28 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_auto_20190528_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformdata',
            old_name='locations',
            new_name='location',
        ),
    ]
